package com.juebingliu.boot4learn.mapper.primary;

import com.juebingliu.boot4learn.domain.primary.CrawlerContent;
import com.juebingliu.boot4learn.domain.primary.CrawlerContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlerContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int countByExample(CrawlerContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int deleteByExample(CrawlerContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int insert(CrawlerContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int insertSelective(CrawlerContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    List<CrawlerContent> selectByExample(CrawlerContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    CrawlerContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") CrawlerContent record, @Param("example") CrawlerContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int updateByExample(@Param("record") CrawlerContent record, @Param("example") CrawlerContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int updateByPrimaryKeySelective(CrawlerContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crawler_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    int updateByPrimaryKey(CrawlerContent record);
}