package com.juebingliu.boot4learn.domain.primary;

public class Bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.order_id
     *
     * @mbggenerated Tue Dec 11 11:31:42 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.amount
     *
     * @mbggenerated Tue Dec 11 11:31:42 CST 2018
     */
    private Long amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.order_id
     *
     * @return the value of bill.order_id
     *
     * @mbggenerated Tue Dec 11 11:31:42 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.order_id
     *
     * @param orderId the value for bill.order_id
     *
     * @mbggenerated Tue Dec 11 11:31:42 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.amount
     *
     * @return the value of bill.amount
     *
     * @mbggenerated Tue Dec 11 11:31:42 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.amount
     *
     * @param amount the value for bill.amount
     *
     * @mbggenerated Tue Dec 11 11:31:42 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        return "Bill{" +
                "orderId='" + orderId + '\'' +
                ", amount=" + amount +
                '}';
    }
}