package com.juebingliu.boot4learn.domain.primary;

import java.util.Date;

public class CrawlerContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_content.id
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_content.publish_time
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_content.publish_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    private String publishContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crawler_content.crawler_time
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    private Date crawlerTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_content.id
     *
     * @return the value of crawler_content.id
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_content.id
     *
     * @param id the value for crawler_content.id
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_content.publish_time
     *
     * @return the value of crawler_content.publish_time
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_content.publish_time
     *
     * @param publishTime the value for crawler_content.publish_time
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_content.publish_content
     *
     * @return the value of crawler_content.publish_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public String getPublishContent() {
        return publishContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_content.publish_content
     *
     * @param publishContent the value for crawler_content.publish_content
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public void setPublishContent(String publishContent) {
        this.publishContent = publishContent == null ? null : publishContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crawler_content.crawler_time
     *
     * @return the value of crawler_content.crawler_time
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public Date getCrawlerTime() {
        return crawlerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crawler_content.crawler_time
     *
     * @param crawlerTime the value for crawler_content.crawler_time
     *
     * @mbggenerated Wed Jun 05 13:18:41 CST 2019
     */
    public void setCrawlerTime(Date crawlerTime) {
        this.crawlerTime = crawlerTime;
    }
}