package com.juebingliu.boot4learn.mapper.secondary;

import com.juebingliu.boot4learn.domain.secondary.Accinfo;
import com.juebingliu.boot4learn.domain.secondary.AccinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int countByExample(AccinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int deleteByExample(AccinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int insert(Accinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int insertSelective(Accinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    List<Accinfo> selectByExample(AccinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    Accinfo selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Accinfo record, @Param("example") AccinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int updateByExample(@Param("record") Accinfo record, @Param("example") AccinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int updateByPrimaryKeySelective(Accinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accinfo
     *
     * @mbggenerated Tue Dec 11 11:33:01 CST 2018
     */
    int updateByPrimaryKey(Accinfo record);
}